name: PostgreSQL Service Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: --health-cmd "pg_isready -U testuser" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Wait for PostgreSQL to be Ready
        run: |
          until nc -z -v -w30 localhost 5432; do
            echo "Waiting for PostgreSQL..."
            sleep 1
          done
          echo "PostgreSQL is ready!"

      - name: Confirm PostgreSQL is Running
        run: |
          PGPASSWORD=testpassword psql -h localhost -U testuser -d testdb -c "SELECT 'PostgreSQL Service Running' AS status;"
